name: 🚀 Publish
on:
  push:
    branches:
    - main

env:
  HUSKY: 0

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Publish
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.x
          branch: main
          extends: |
            @semantic-release/git@10.0.1
            @semantic-release/changelog@6.0.2
            @commitlint/cli@17.3.0
            @commitlint/config-conventional@17.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
